brave/slim-list-lambda

slim-list-lambdas.yaml

requires for https://github.com/brave/devops/issues/2991

add alarm action and metric filter for lambda

---

slim-list-lambdas.yaml

requires for https://github.com/brave/devops/issues/3405

Add minimum invocation period monitoring for Slim List lambdas

---

README.md
brave/db.js
brave/lambda.js
brave/lambda_actions/assemble.js
brave/lambda_actions/build.js
brave/s3.js
brave/sqs.js
index.js
package-lock.json
package.json
slim-list-lambda-configuration.json
slim-list-lambdas.yaml

Release includes the following:
- `assemble` lambda
- CloudWatch Metrics/Alarms associated with `assemble` lambda

Release 2020-09-05

---

brave/lambda_actions/assemble.js
brave/lambda_actions/build.js

Update readACL for adblock private

---

brave/lambda_actions/assemble.js
brave/lambda_actions/build.js

Update readAcl input arg

---

slim-list-lambdas.yaml

Add readACL for adblock private

---

Makefile
brave/lambda_actions/assemble.js
brave/lambda_actions/build.js
brave/lambda_actions/crawl-dispatch.js
brave/lambda_actions/crawl.js
brave/s3.js
build.sh

Requires for https://github.com/brave/devops/issues/4439

Remove bucket owner ACL

---

slim-list-lambdas.yaml

Closes https://github.com/brave/devops/issues/4528

Remove wrong CW alarms

---

README.md

Requires for https://github.com/brave/devops/issues/5033

Change branch and deployment semantics

---

Makefile

For https://github.com/brave/devops/issues/8418

updated docker images

---

Dockerfile
Makefile
build.sh
package-lock.json
package.json
slim-list-lambdas.yaml

For https://github.com/brave/devops/issues/8131

Upgrade to nodejs16.x runtime

---

brave/lambda_actions/crawl.js

Signed-off-by: Ahmed Kamal <email.ahmedkamal@googlemail.com>

Use waitForTimeout

---

brave/adblock.js
brave/lambda_actions/assemble.js
package-lock.json
package.json

Note: I haven't tested this, it would be great to run it in a staging environment if possible.

Update adblock-rust to v0.7.5

---

brave/lambda_actions/assemble.js
slim-list-lambdas.yaml

- change argument to addFilters to be an object
- Fix for Assmble lambda to mitigate segfault
- Fixed Ephemeral Storage attribute for Assemble Lambda Function
- Removed trailing space

Release 2023-04-02

---

brave/lambda_actions/assemble.js

ports #73, #75 to `production`

rule_types should be on addFilters, not FilterSet constructor

---

brave/lambda_actions/assemble.js

Code changes to support the upcoming format update in https://github.com/brave/adblock-resources/pull/103

New list catalog format

---

Makefile
brave/lambda_actions/assemble.js

Bump xml2js and adblock-rust (`production`)

---

brave/lambda_actions/assemble.js
brave/lambda_actions/crawl-dispatch.js
brave/tranco.js
package-lock.json
package.json

See https://bravesoftware.slack.com/archives/C8MP8ME4C/p1689041024489009

Replace request dependencies with native fetch

---

Makefile
brave/adblock.js
brave/lambda_actions/assemble.js
brave/lambda_actions/crawl-dispatch.js
brave/tranco.js
package-lock.json
package.json
slim-list-lambdas.yaml

Resync `production`

---

brave/lambda.js
brave/s3.js
brave/sqs.js
package-lock.json
package.json

AWS SDK v3

---

Dockerfile
Makefile
brave/s3.js

- Update Dockerfile
- Update Makefile

Release 2023-09-20

---

Dockerfile
Makefile
brave/s3.js
build.sh

- Update Dockerfile
- Update Makefile
- Update build.sh to include nss (#99)

Release 2023-09-25

---

brave/lambda_actions/assemble.js

needs a `production` PR as well

add newer brave-unbreak URL
